# Generated by Django 2.2 on 2021-02-09 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_firma_founders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firma',
            name='url_minjust_site',
        ),
    ]
