# Generated by Django 2.2 on 2021-02-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_firma_url_minjust_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='firma',
            name='url_minjust_site',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на сайт'),
        ),
    ]
