# Generated by Django 2.2 on 2021-02-10 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_firma_url_minjust_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firma',
            name='full_name_kg',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Полное наименование kg'),
        ),
    ]
