# Generated by Django 2.2 on 2021-02-11 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210210_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openbudget',
            name='period',
        ),
    ]
