# Generated by Django 2.2 on 2021-02-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20210212_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='count_of_lots',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Количество лотов'),
        ),
    ]
