# Generated by Django 2.2 on 2021-02-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20210217_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='condition',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Условие поставки'),
        ),
    ]
