# Generated by Django 2.2 on 2021-02-17 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20210217_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification',
        ),
    ]
