# Generated by Django 2.2 on 2021-02-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_product_specification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winner',
            name='canceled_reason',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='winner',
            name='winner_name',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Название победителя'),
        ),
    ]
