# Generated by Django 2.2 on 2021-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20210217_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='tax_status',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Налог статус'),
        ),
    ]
