# Generated by Django 2.2 on 2021-02-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20210218_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='org_name',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Название организации'),
        ),
    ]
