# Generated by Django 2.2 on 2021-04-09 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0023_auto_20210218_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supliers',
            name='address',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='bank',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Банк'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='checking_account',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='city',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='form',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Форма собственности'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Наименование организации'),
        ),
        migrations.AlterField(
            model_name='supliers',
            name='reg_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дата регистрации'),
        ),
    ]
